/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ashnikoo.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ashnikoo.gltf')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Root} />
      <skinnedMesh geometry={nodes.Bodybaked.geometry} material={materials.F00_003_01_Body_00_SKIN} skeleton={nodes.Bodybaked.skeleton} />
      <skinnedMesh geometry={nodes.Bodybaked_1.geometry} material={materials.F00_006_01_Tops_01_CLOTH} skeleton={nodes.Bodybaked_1.skeleton} />
      <skinnedMesh geometry={nodes.Bodybaked_2.geometry} material={materials.F00_008_01_Bottoms_01_CLOTH} skeleton={nodes.Bodybaked_2.skeleton} />
      <skinnedMesh geometry={nodes.Bodybaked_3.geometry} material={materials.F00_005_01_Shoes_01_CLOTH} skeleton={nodes.Bodybaked_3.skeleton} />
      <skinnedMesh geometry={nodes.Bodybaked_4.geometry} material={materials.F00_000_HairBack_00_HAIR} skeleton={nodes.Bodybaked_4.skeleton} />
      <skinnedMesh geometry={nodes.Hair001baked.geometry} material={materials.F00_000_Hair_00_HAIR_01} skeleton={nodes.Hair001baked.skeleton} />
      <skinnedMesh geometry={nodes.Hair001baked_1.geometry} material={materials.F00_000_Hair_00_HAIR_02} skeleton={nodes.Hair001baked_1.skeleton} />
      <skinnedMesh name="Facebaked" geometry={nodes.Facebaked.geometry} material={materials.F00_000_00_FaceMouth_00_FACE} skeleton={nodes.Facebaked.skeleton} morphTargetDictionary={nodes.Facebaked.morphTargetDictionary} morphTargetInfluences={nodes.Facebaked.morphTargetInfluences} />
      <skinnedMesh name="Facebaked_1" geometry={nodes.Facebaked_1.geometry} material={materials.F00_000_00_EyeWhite_00_EYE} skeleton={nodes.Facebaked_1.skeleton} morphTargetDictionary={nodes.Facebaked_1.morphTargetDictionary} morphTargetInfluences={nodes.Facebaked_1.morphTargetInfluences} />
      <skinnedMesh name="Facebaked_2" geometry={nodes.Facebaked_2.geometry} material={materials.F00_000_00_FaceEyeline_00_FACE} skeleton={nodes.Facebaked_2.skeleton} morphTargetDictionary={nodes.Facebaked_2.morphTargetDictionary} morphTargetInfluences={nodes.Facebaked_2.morphTargetInfluences} />
      <skinnedMesh name="Facebaked_3" geometry={nodes.Facebaked_3.geometry} material={materials.F00_000_00_FaceEyelash_00_FACE} skeleton={nodes.Facebaked_3.skeleton} morphTargetDictionary={nodes.Facebaked_3.morphTargetDictionary} morphTargetInfluences={nodes.Facebaked_3.morphTargetInfluences} />
      <skinnedMesh name="Facebaked_4" geometry={nodes.Facebaked_4.geometry} material={materials.F00_000_00_FaceBrow_00_FACE} skeleton={nodes.Facebaked_4.skeleton} morphTargetDictionary={nodes.Facebaked_4.morphTargetDictionary} morphTargetInfluences={nodes.Facebaked_4.morphTargetInfluences} />
      <skinnedMesh name="Facebaked_5" geometry={nodes.Facebaked_5.geometry} material={materials.F00_000_00_EyeIris_00_EYE} skeleton={nodes.Facebaked_5.skeleton} morphTargetDictionary={nodes.Facebaked_5.morphTargetDictionary} morphTargetInfluences={nodes.Facebaked_5.morphTargetInfluences} />
      <skinnedMesh name="Facebaked_6" geometry={nodes.Facebaked_6.geometry} material={materials.F00_000_00_EyeHighlight_00_EYE} skeleton={nodes.Facebaked_6.skeleton} morphTargetDictionary={nodes.Facebaked_6.morphTargetDictionary} morphTargetInfluences={nodes.Facebaked_6.morphTargetInfluences} />
      <skinnedMesh name="Facebaked_7" geometry={nodes.Facebaked_7.geometry} material={materials.F00_000_00_Face_00_SKIN} skeleton={nodes.Facebaked_7.skeleton} morphTargetDictionary={nodes.Facebaked_7.morphTargetDictionary} morphTargetInfluences={nodes.Facebaked_7.morphTargetInfluences} />
      <skinnedMesh name="Facebaked_8" geometry={nodes.Facebaked_8.geometry} material={materials.F00_000_00_EyeExtra_01_EYE} skeleton={nodes.Facebaked_8.skeleton} morphTargetDictionary={nodes.Facebaked_8.morphTargetDictionary} morphTargetInfluences={nodes.Facebaked_8.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('/ashnikoo.gltf')
